#!/bin/bash 

source context

docker compose \
    -f ${TEMPLATE_ROOT}/compose/docker-compose.${PROJECT_MODE}.yml \
    -f ${TEMPLATE_ROOT}/compose/routers/compose.${PROJECT_ROUTER}.yml \
    --env-file ${PROJECT_ROOT}/.env \
    --env-file ${PROJECT_SECRETS_FILE} \
    $@
