#!/bin/bash 

source context

docker compose \
    -f compose/docker-compose.${PROJECT_MODE}.yml \
    -f compose/routers/compose.${PROJECT_ROUTER}.yml \
    --env-file .env \
    --env-file .env.secrets \
    $@
