#!/bin/bash 

sudo echo -n ""

# Load configuration.
echo "Loading configuration..."
source .env 

# Make install directory.
echo "Making installation directory..."
sudo mkdir -p ${DFST_INSTALL_DIR}
 
# Copy files in install directory.
echo "Linking files in installation directory..." 
sudo ln -s $(pwd) ${DFST_INSTALL_DIR}/${DFST_SUBNAME}

# Program finished.
echo "Done."

