#!/bin/bash
echo "Installing DFST..."

git clone --depth=1 https://github.com/lvjhn0xff/dfst.git /tmp/dfst 
cd /tmp/dfst 
bash install
echo "DFS1_PATH=/opt/dfst/1/main" >> ~/.bashrc

echo "Successfully installed..."
echo "Done."