#!/bin/bash 
source context 

echo ":: Check if certificates should be updated." 
bash utils/local/certs/auto-update-certs

echo ":: Running services in detached mode."
bash docker-compose up -d 

echo ":: Updating DNS entries"
bash utils/dns-update
