entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

# Enable Docker & file providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

# Enable Traefik dashboard
api:
  dashboard: true

# --- Let's Encrypt ACME ---
certificatesResolvers:
  letsencrypt:
    acme:
      email: example@gmail.com
      storage: "/acme.json"
      httpChallenge:
        entryPoint: web
