#!/bin/bash
set -euo pipefail

# Ensure context file exists
if [ ! -f context ]; then
  echo "❌ Error: 'context' file not found."
  exit 1
fi
source context

echo ":: Publishing DNS entries."

# Direct stream (no temp file)
bash utils/dns-entry | docker exec -i "${COREDNS_CONTAINER_NAME}-debug" \
  sh -c "
    # Create file.
    cat > /zones/${PROJECT_NAME}.conf && 

    # Fix permissions
    chmod 644 /zones/${PROJECT_NAME}.conf
  "

echo "✅ Done."
