#!/bin/bash 
source context 

DATE_TO_CHECK=$(cat "$TEMPLATE_ROOT/certs/renew-date")
NOW=$(date +%s)
TARGET=$(date -d "$DATE_TO_CHECK" +%s)

if (( NOW > TARGET )); then
    echo "----- Certificates expired, updating."
    bash utils/local/certs/issue-certs
    
    echo "----- Updating/reloading router." 
    docker kill -s HUP router
else
    echo "----- Certificates not yet expired, not updating."
fi